import {
  Prisma,
  type Client,
  type ClientStatus,
  type AuditAction,
} from "@prisma/client";

import { prisma } from "@/server/db";
import { recordAudit } from "@/server/audit/log";
import type {
  CreateClientInput,
  UpdateClientInput,
  ClientStatusAction,
} from "@/lib/validation/client";

/**
 * Client Management service layer. All business logic + database access for
 * clients lives here; route handlers and server components call these
 * functions and never touch Prisma directly.
 *
 * Security: every caller has already passed `authorizeAdminApi()` /
 * `requireSuperAdmin()`. `adminUserId` is taken from the signed session by
 * the caller — it is never read from the request body.
 */

export type ClientListItem = Pick<
  Client,
  | "id"
  | "clientId"
  | "name"
  | "website"
  | "domain"
  | "status"
  | "createdAt"
  | "updatedAt"
>;

export type ClientDetail = Client & {
  _count: { subscriptions: number; callLogs: number };
};

export type ClientServiceErrorCode = "NOT_FOUND" | "CONFLICT";

export class ClientServiceError extends Error {
  constructor(
    readonly code: ClientServiceErrorCode,
    message: string,
    /** Optional field-scoped errors for a 409 the form can render inline. */
    readonly fieldErrors?: Record<string, string[]>,
  ) {
    super(message);
    this.name = "ClientServiceError";
  }
}

/** Map a service error to an HTTP status, or `null` if it isn't one of ours. */
export function clientErrorStatus(err: unknown): number | null {
  if (!(err instanceof ClientServiceError)) return null;
  return err.code === "NOT_FOUND" ? 404 : 409;
}

const LIST_SELECT = {
  id: true,
  clientId: true,
  name: true,
  website: true,
  domain: true,
  status: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.ClientSelect;

const STATUS_ACTION_MAP: Record<
  ClientStatusAction,
  { status: ClientStatus; audit: AuditAction }
> = {
  SUSPEND: { status: "SUSPENDED", audit: "CLIENT_SUSPENDED" },
  ACTIVATE: { status: "ACTIVE", audit: "CLIENT_ACTIVATED" },
  DEACTIVATE: { status: "INACTIVE", audit: "CLIENT_DEACTIVATED" },
};

/** List clients, newest first, with optional server-side search. */
export async function listClients(
  opts: { q?: string } = {},
): Promise<ClientListItem[]> {
  const q = opts.q?.trim();
  const where: Prisma.ClientWhereInput =
    q && q.length > 0
      ? {
          OR: [
            { name: { contains: q, mode: "insensitive" } },
            { clientId: { contains: q, mode: "insensitive" } },
            { domain: { contains: q, mode: "insensitive" } },
            { website: { contains: q, mode: "insensitive" } },
          ],
        }
      : {};

  return prisma.client.findMany({
    where,
    select: LIST_SELECT,
    orderBy: { createdAt: "desc" },
    take: 200,
  });
}

export async function getClient(id: string): Promise<ClientDetail> {
  const client = await prisma.client.findUnique({
    where: { id },
    include: { _count: { select: { subscriptions: true, callLogs: true } } },
  });
  if (!client) {
    throw new ClientServiceError("NOT_FOUND", "Client not found");
  }
  return client;
}

async function assertDomainAvailable(
  domain: string,
  exceptId?: string,
): Promise<void> {
  const existing = await prisma.client.findFirst({
    where: { domain, ...(exceptId ? { NOT: { id: exceptId } } : {}) },
    select: { id: true },
  });
  if (existing) {
    throw new ClientServiceError(
      "CONFLICT",
      "Another client already uses this domain",
      { domain: ["Another client already uses this domain"] },
    );
  }
}

export async function createClient(
  input: CreateClientInput,
  adminUserId: string,
): Promise<Client> {
  if (input.domain) await assertDomainAvailable(input.domain);

  return prisma.$transaction(async (tx) => {
    // `clientId` (NC-CL-000001) is generated by the Postgres sequence via a
    // dbgenerated default — never supplied here.
    const client = await tx.client.create({
      data: {
        name: input.name,
        website: input.website ?? null,
        domain: input.domain ?? null,
      },
    });

    await recordAudit({
      adminUserId,
      action: "CLIENT_CREATED",
      targetType: "Client",
      targetId: client.id,
      metadata: {
        clientId: client.clientId,
        name: client.name,
        website: client.website,
        domain: client.domain,
      },
      tx,
    });

    return client;
  });
}

export async function updateClient(
  id: string,
  input: UpdateClientInput,
  adminUserId: string,
): Promise<Client> {
  const current = await prisma.client.findUnique({ where: { id } });
  if (!current) throw new ClientServiceError("NOT_FOUND", "Client not found");

  const nextDomain = input.domain ?? null;
  if (nextDomain && nextDomain !== current.domain) {
    await assertDomainAvailable(nextDomain, id);
  }

  const nextWebsite = input.website ?? null;

  return prisma.$transaction(async (tx) => {
    const client = await tx.client.update({
      where: { id },
      data: { name: input.name, website: nextWebsite, domain: nextDomain },
    });

    const changed: Record<string, { from: string | null; to: string | null }> =
      {};
    if (current.name !== client.name)
      changed.name = { from: current.name, to: client.name };
    if (current.website !== client.website)
      changed.website = { from: current.website, to: client.website };
    if (current.domain !== client.domain)
      changed.domain = { from: current.domain, to: client.domain };

    await recordAudit({
      adminUserId,
      action: "CLIENT_UPDATED",
      targetType: "Client",
      targetId: client.id,
      metadata: { clientId: client.clientId, changed },
      tx,
    });

    return client;
  });
}

/**
 * Suspend / Activate / Deactivate a client. Deactivate is a soft-delete:
 * the row and all dependent history are preserved. Idempotent — a no-op
 * transition writes no audit row.
 */
export async function setClientStatus(
  id: string,
  action: ClientStatusAction,
  adminUserId: string,
): Promise<Client> {
  const target = STATUS_ACTION_MAP[action];
  const current = await prisma.client.findUnique({ where: { id } });
  if (!current) throw new ClientServiceError("NOT_FOUND", "Client not found");

  if (current.status === target.status) return current;

  return prisma.$transaction(async (tx) => {
    const client = await tx.client.update({
      where: { id },
      data: { status: target.status },
    });

    await recordAudit({
      adminUserId,
      action: target.audit,
      targetType: "Client",
      targetId: client.id,
      metadata: {
        clientId: client.clientId,
        from: current.status,
        to: client.status,
      },
      tx,
    });

    return client;
  });
}
